my_project_directory/src/Entity/Video.php
<?php

namespace App\Entity;

use App\Repository\VideoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VideoRepository::class)]
class Video
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?int $category_id = null;

    #[ORM\Column(length: 255)]
    private ?string $youtoube_id = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCategoryId(): ?int
    {
        return $this->category_id;
    }

    public function setCategoryId(int $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    public function getYoutoubeId(): ?string
    {
        return $this->youtoube_id;
    }

    public function setYoutoubeId(string $youtoube_id): self
    {
        $this->youtoube_id = $youtoube_id;

        return $this;
    }
}

my_project_directory/src/Controller/VideoController.php
<?php

namespace App\Controller;

use App\Entity\Video;
use Container7YheZem\getDoctrine_UlidGeneratorService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use App\Repository\ConferenceRepository;
use Twig\Environment;

class VideoController extends AbstractController
{
    #[Route('/video', name: 'app_video')]
    public function Show(ManagerRegistry $doctrine): Response
    {

        $videos = $doctrine->getRepository(Video::class)->findAll();
        // dump($videos);die;

        return $this->render('video/index.html.twig', ['videos' => $videos]);
    }



    #[Route('/show_video/{youtoube_id}', name: 'show_video')]
     
    public function Showonevideo(ManagerRegistry $doctrine, $youtoube_id): Response

    {

        $video = $doctrine->getRepository(Video::class)-> findOneBy(['youtoube_id' => $youtoube_id]);
        //  dump($video);die;

        return $this->render('video/showOneVideo.html.twig', ['video' => $video]);
    }



    
    #[Route('/show_video_by_cat/{category_id}', name: 'show_video_by_cat')]
     
    public function ShowByCategory(ManagerRegistry $doctrine, $category_id): Response

    {

        $videos = $doctrine->getRepository(Video::class)-> findBy(['category_id' => $category_id]);
        //  dump($video);die;

        return $this->render('video/index.html.twig', ['videos' => $videos]);
    }


 
}

my_project_directory/templates/video/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Мои видео{% endblock %}
{% block main_cont %}


<h1>Show Video</h1>
    <div class = "grid">
        {% for video in videos %}
        
        <div class="grid_item">
       
       <h4><a href = "{{path('show_video', {youtoube_id: video.youtoubeId}) }}"> {{ video.title }}</a></h4><br> 
          
                <iframe width = "350" height = "197" src = "https://www.youtube.com/embed/{{video.youtoubeId}}" frameborder = "0" allowe = "accelerometr; autoplay; encrypted-media; gyroscope; picture-in-picture"</iframe>
        </div>
    {% endfor %}
    </div>
{% endblock %}

my_project_directory/templates/video/showOneVideo.html.twig
{% extends 'base.html.twig' %}

{% block main_cont %}

<h1>{{video.title}}</h1>
    <div class = "grid">
       
        
        <div class="grid_item">
   
          
                <iframe width = "560" height = "315" src = "https://www.youtube.com/embed/{{video.youtoubeId}}" frameborder = "0" allowe = "accelerometr; autoplay; encrypted-media; gyroscope; picture-in-picture"</iframe>
        </div>
   
    </div>
{% endblock %}